#pragma once

#include <cstddef>
#include <cstdint>

namespace mips32
{

struct Token
{
  enum
  {
    UNKNOWN = 0,

    LABEL_DECL,
    LABEL_REF,
    DIRECTIVE,
    INSTRUCTION,
    INT_REGISTER,
    FLOAT_REGISTER,
    COMMENT,
    INTEGER,
    FLOAT,
    STRING,
    COMMA,     // no data
    LEFT_PAR,  // no data
    RIGHT_PAR, // no data
    NEWLINE,   // no data
  } type = UNKNOWN;

  union
  {
    // register
    std::uint32_t reg;

    // numbers
    std::uint32_t u32;
    double f64;

    // label decl/ref
    std::size_t hash;

    // directive, instruction
    int code;
    
    // non owning view
    // string or comment
    struct
    {
      char const *data;
      int size;
    } str;
  };
};

inline constexpr int D_WORD{13};
inline constexpr int D_TEXT{12};
inline constexpr int D_SPACE{11};
inline constexpr int D_KTEXT{10};
inline constexpr int D_KDATA{9};
inline constexpr int D_HALF{8};
inline constexpr int D_GLOBL{7};
inline constexpr int D_FLOAT{6};
inline constexpr int D_DOUBLE{5};
inline constexpr int D_DATA{4};
inline constexpr int D_BYTE{3};
inline constexpr int D_ASCIIZ{2};
inline constexpr int D_ASCII{1};
inline constexpr int D_ALIGN{0};

inline constexpr int I_ABS_S{ 500 };
inline constexpr int I_ABS_D{ 499 };
inline constexpr int I_ADD{ 498 };
inline constexpr int I_ADD_S{ 497 };
inline constexpr int I_ADD_D{ 496 };
inline constexpr int I_ADDI{ 495 };
inline constexpr int I_ADDIU{ 494 };
inline constexpr int I_ADDIUPC{ 493 };
inline constexpr int I_ADDU{ 492 };
inline constexpr int I_ALIGN{ 491 };
inline constexpr int I_ALNV_PS{ 490 };
inline constexpr int I_ALUIPC{ 489 };
inline constexpr int I_AND{ 488 };
inline constexpr int I_ANDI{ 487 };
inline constexpr int I_AUI{ 486 };
inline constexpr int I_AUIPC{ 485 };
inline constexpr int I_B{ 484 };
inline constexpr int I_BAL{ 483 };
inline constexpr int I_BALC{ 482 };
inline constexpr int I_BC{ 481 };
inline constexpr int I_BCEQZ{ 480 };
inline constexpr int I_BCNEZ{ 479 };
inline constexpr int I_BCF{ 478 };
inline constexpr int I_BCFL{ 477 };
inline constexpr int I_BCT{ 476 };
inline constexpr int I_BCTL{ 475 };
inline constexpr int I_BEQ{ 474 };
inline constexpr int I_BEQL{ 473 };
inline constexpr int I_BGEZ{ 472 };
inline constexpr int I_BGEZAL{ 471 };
inline constexpr int I_BLEZALC{ 470 };
inline constexpr int I_BGEZALC{ 469 };
inline constexpr int I_BGTZALC{ 468 };
inline constexpr int I_BLTZALC{ 467 };
inline constexpr int I_BEQZALC{ 466 };
inline constexpr int I_BNEZALC{ 465 };
inline constexpr int I_BGEZALL{ 464 };
inline constexpr int I_BEQC{ 463 };
inline constexpr int I_BNEC{ 462 };
inline constexpr int I_BLTC{ 461 };
inline constexpr int I_BGEC{ 460 };
inline constexpr int I_BLTUC{ 459 };
inline constexpr int I_BGEUC{ 458 };
inline constexpr int I_BGTC{ 457 };
inline constexpr int I_BLEC{ 456 };
inline constexpr int I_BGTUC{ 455 };
inline constexpr int I_BLEUC{ 454 };
inline constexpr int I_BLTZC{ 453 };
inline constexpr int I_BLEZC{ 452 };
inline constexpr int I_BGEZC{ 451 };
inline constexpr int I_BGTZC{ 450 };
inline constexpr int I_BEQZC{ 449 };
inline constexpr int I_BNEZC{ 448 };
inline constexpr int I_BGEZL{ 447 };
inline constexpr int I_BGTZ{ 446 };
inline constexpr int I_BGTZL{ 445 };
inline constexpr int I_BITSWAP{ 444 };
inline constexpr int I_BLEZ{ 443 };
inline constexpr int I_BLEZL{ 442 };
inline constexpr int I_BLTZ{ 441 };
inline constexpr int I_BLTZAL{ 440 };
inline constexpr int I_BLTZALL{ 439 };
inline constexpr int I_BLTZL{ 438 };
inline constexpr int I_BNE{ 437 };
inline constexpr int I_BNEL{ 436 };
inline constexpr int I_BOVC{ 435 };
inline constexpr int I_BNVC{ 434 };
inline constexpr int I_BREAK{ 433 };
inline constexpr int I_C_F_S{ 432 };
inline constexpr int I_C_F_D{ 431 };
inline constexpr int I_C_F_PS{ 430 };
inline constexpr int I_C_UN_S{ 429 };
inline constexpr int I_C_UN_D{ 428 };
inline constexpr int I_C_UN_PS{ 427 };
inline constexpr int I_C_EQ_S{ 426 };
inline constexpr int I_C_EQ_D{ 425 };
inline constexpr int I_C_EQ_PS{ 424 };
inline constexpr int I_C_UEQ_S{ 423 };
inline constexpr int I_C_UEQ_D{ 422 };
inline constexpr int I_C_UEQ_PS{ 421 };
inline constexpr int I_C_OLT_S{ 420 };
inline constexpr int I_C_OLT_D{ 419 };
inline constexpr int I_C_OLT_PS{ 418 };
inline constexpr int I_C_ULT_S{ 417 };
inline constexpr int I_C_ULT_D{ 416 };
inline constexpr int I_C_ULT_PS{ 415 };
inline constexpr int I_C_OLE_S{ 414 };
inline constexpr int I_C_OLE_D{ 413 };
inline constexpr int I_C_OLE_PS{ 412 };
inline constexpr int I_C_ULE_S{ 411 };
inline constexpr int I_C_ULE_D{ 410 };
inline constexpr int I_C_ULE_PS{ 409 };
inline constexpr int I_C_SF_S{ 408 };
inline constexpr int I_C_SF_D{ 407 };
inline constexpr int I_C_SF_PS{ 406 };
inline constexpr int I_C_NGLE_S{ 405 };
inline constexpr int I_C_NGLE_D{ 404 };
inline constexpr int I_C_NGLE_PS{ 403 };
inline constexpr int I_C_SEQ_S{ 402 };
inline constexpr int I_C_SEQ_D{ 401 };
inline constexpr int I_C_SEQ_PS{ 400 };
inline constexpr int I_C_NGL_S{ 399 };
inline constexpr int I_C_NGL_D{ 398 };
inline constexpr int I_C_NGL_PS{ 397 };
inline constexpr int I_C_LT_S{ 396 };
inline constexpr int I_C_LT_D{ 395 };
inline constexpr int I_C_LT_PS{ 394 };
inline constexpr int I_C_NGE_S{ 393 };
inline constexpr int I_C_NGE_D{ 392 };
inline constexpr int I_C_NGE_PS{ 391 };
inline constexpr int I_C_LE_S{ 390 };
inline constexpr int I_C_LE_D{ 389 };
inline constexpr int I_C_LE_PS{ 388 };
inline constexpr int I_C_NGT_S{ 387 };
inline constexpr int I_C_NGT_D{ 386 };
inline constexpr int I_C_NGT_PS{ 385 };
inline constexpr int I_C_T_S{ 384 };
inline constexpr int I_C_T_D{ 383 };
inline constexpr int I_C_T_PS{ 382 };
inline constexpr int I_C_OR_S{ 381 };
inline constexpr int I_C_OR_D{ 380 };
inline constexpr int I_C_OR_PS{ 379 };
inline constexpr int I_C_NEQ_S{ 378 };
inline constexpr int I_C_NEQ_D{ 377 };
inline constexpr int I_C_NEQ_PS{ 376 };
inline constexpr int I_C_OGL_S{ 375 };
inline constexpr int I_C_OGL_D{ 374 };
inline constexpr int I_C_OGL_PS{ 373 };
inline constexpr int I_C_UGE_S{ 372 };
inline constexpr int I_C_UGE_D{ 371 };
inline constexpr int I_C_UGE_PS{ 370 };
inline constexpr int I_C_OGE_S{ 369 };
inline constexpr int I_C_OGE_D{ 368 };
inline constexpr int I_C_OGE_PS{ 367 };
inline constexpr int I_C_UGT_S{ 366 };
inline constexpr int I_C_UGT_D{ 365 };
inline constexpr int I_C_UGT_PS{ 364 };
inline constexpr int I_C_OGT_S{ 363 };
inline constexpr int I_C_OGT_D{ 362 };
inline constexpr int I_C_OGT_PS{ 361 };
inline constexpr int I_C_ST_S{ 360 };
inline constexpr int I_C_ST_D{ 359 };
inline constexpr int I_C_ST_PS{ 358 };
inline constexpr int I_C_GLE_S{ 357 };
inline constexpr int I_C_GLE_D{ 356 };
inline constexpr int I_C_GLE_PS{ 355 };
inline constexpr int I_C_SNE_S{ 354 };
inline constexpr int I_C_SNE_D{ 353 };
inline constexpr int I_C_SNE_PS{ 352 };
inline constexpr int I_C_GL_S{ 351 };
inline constexpr int I_C_GL_D{ 350 };
inline constexpr int I_C_GL_PS{ 349 };
inline constexpr int I_C_NLT_S{ 348 };
inline constexpr int I_C_NLT_D{ 347 };
inline constexpr int I_C_NLT_PS{ 346 };
inline constexpr int I_C_GE_S{ 345 };
inline constexpr int I_C_GE_D{ 344 };
inline constexpr int I_C_GE_PS{ 343 };
inline constexpr int I_C_NLE_S{ 342 };
inline constexpr int I_C_NLE_D{ 341 };
inline constexpr int I_C_NLE_PS{ 340 };
inline constexpr int I_C_GT_S{ 339 };
inline constexpr int I_C_GT_D{ 338 };
inline constexpr int I_C_GT_PS{ 337 };
inline constexpr int I_CACHE{ 336 };
inline constexpr int I_CACHEE{ 335 };
inline constexpr int I_CEIL_L_S{ 334 };
inline constexpr int I_CEIL_L_D{ 333 };
inline constexpr int I_CEIL_W_S{ 332 };
inline constexpr int I_CEIL_W_D{ 331 };
inline constexpr int I_CFC{ 330 };
inline constexpr int I_CLASS_S{ 329 };
inline constexpr int I_CLASS_D{ 328 };
inline constexpr int I_CLO{ 327 };
inline constexpr int I_CLZ{ 326 };
inline constexpr int I_CMP_AF_S{ 325 };
inline constexpr int I_CMP_AF_D{ 324 };
inline constexpr int I_CMP_UN_S{ 323 };
inline constexpr int I_CMP_UN_D{ 322 };
inline constexpr int I_CMP_EQ_S{ 321 };
inline constexpr int I_CMP_EQ_D{ 320 };
inline constexpr int I_CMP_UEQ_S{ 319 };
inline constexpr int I_CMP_UEQ_D{ 318 };
inline constexpr int I_CMP_LT_S{ 317 };
inline constexpr int I_CMP_LT_D{ 316 };
inline constexpr int I_CMP_ULT_S{ 315 };
inline constexpr int I_CMP_ULT_D{ 314 };
inline constexpr int I_CMP_LE_S{ 313 };
inline constexpr int I_CMP_LE_D{ 312 };
inline constexpr int I_CMP_ULE_S{ 311 };
inline constexpr int I_CMP_ULE_D{ 310 };
inline constexpr int I_CMP_SAF_S{ 309 };
inline constexpr int I_CMP_SAF_D{ 308 };
inline constexpr int I_CMP_SUN_S{ 307 };
inline constexpr int I_CMP_SUN_D{ 306 };
inline constexpr int I_CMP_SEQ_S{ 305 };
inline constexpr int I_CMP_SEQ_D{ 304 };
inline constexpr int I_CMP_SUEQ_S{ 303 };
inline constexpr int I_CMP_SUEQ_D{ 302 };
inline constexpr int I_CMP_SLT_S{ 301 };
inline constexpr int I_CMP_SLT_D{ 300 };
inline constexpr int I_CMP_SULT_S{ 299 };
inline constexpr int I_CMP_SULT_D{ 298 };
inline constexpr int I_CMP_SLE_S{ 297 };
inline constexpr int I_CMP_SLE_D{ 296 };
inline constexpr int I_CMP_SULE_S{ 295 };
inline constexpr int I_CMP_SULE_D{ 294 };
inline constexpr int I_CMP_AT_S{ 293 };
inline constexpr int I_CMP_AT_D{ 292 };
inline constexpr int I_CMP_OR_S{ 291 };
inline constexpr int I_CMP_OR_D{ 290 };
inline constexpr int I_CMP_UNE_S{ 289 };
inline constexpr int I_CMP_UNE_D{ 288 };
inline constexpr int I_CMP_NE_S{ 287 };
inline constexpr int I_CMP_NE_D{ 286 };
inline constexpr int I_CMP_UGE_S{ 285 };
inline constexpr int I_CMP_UGE_D{ 284 };
inline constexpr int I_CMP_OGE_S{ 283 };
inline constexpr int I_CMP_OGE_D{ 282 };
inline constexpr int I_CMP_UGT_S{ 281 };
inline constexpr int I_CMP_UGT_D{ 280 };
inline constexpr int I_CMP_OGT_S{ 279 };
inline constexpr int I_CMP_OGT_D{ 278 };
inline constexpr int I_CMP_SAT_S{ 277 };
inline constexpr int I_CMP_SAT_D{ 276 };
inline constexpr int I_CMP_SOR_S{ 275 };
inline constexpr int I_CMP_SOR_D{ 274 };
inline constexpr int I_CMP_SUNE_S{ 273 };
inline constexpr int I_CMP_SUNE_D{ 272 };
inline constexpr int I_CMP_SNE_S{ 271 };
inline constexpr int I_CMP_SNE_D{ 270 };
inline constexpr int I_CMP_SUGE_S{ 269 };
inline constexpr int I_CMP_SUGE_D{ 268 };
inline constexpr int I_CMP_SOGE_S{ 267 };
inline constexpr int I_CMP_SOGE_D{ 266 };
inline constexpr int I_CMP_SUGT_S{ 265 };
inline constexpr int I_CMP_SUGT_D{ 264 };
inline constexpr int I_CMP_SOGT_S{ 263 };
inline constexpr int I_CMP_SOGT_D{ 262 };
inline constexpr int I_COP{ 261 };
inline constexpr int I_CRCB{ 260 };
inline constexpr int I_CRCH{ 259 };
inline constexpr int I_CRCW{ 258 };
inline constexpr int I_CRCCB{ 257 };
inline constexpr int I_CRCCH{ 256 };
inline constexpr int I_CRCCW{ 255 };
inline constexpr int I_CTC1{ 254 };
inline constexpr int I_CTC2{ 253 };
inline constexpr int I_CVT_D_S{ 252 };
inline constexpr int I_CVT_D_W{ 251 };
inline constexpr int I_CVT_D_L{ 250 };
inline constexpr int I_CVT_L_S{ 249 };
inline constexpr int I_CVT_L_D{ 248 };
inline constexpr int I_CVT_PS_S{ 247 };
inline constexpr int I_CVT_S_PL{ 246 };
inline constexpr int I_CVT_S_PU{ 245 };
inline constexpr int I_CVT_S_D{ 244 };
inline constexpr int I_CVT_S_W{ 243 };
inline constexpr int I_CVT_S_L{ 242 };
inline constexpr int I_CVT_W_S{ 241 };
inline constexpr int I_CVT_W_D{ 240 };
inline constexpr int I_DDIV{ 239 };
inline constexpr int I_DDIVU{ 238 };
inline constexpr int I_DERET{ 237 };
inline constexpr int I_DI{ 236 };
inline constexpr int I_DIV{ 235 };
inline constexpr int I_MOD{ 234 };
inline constexpr int I_DIVU{ 233 };
inline constexpr int I_MODU{ 232 };
inline constexpr int I_DIV_S{ 231 };
inline constexpr int I_DIV_D{ 230 };
inline constexpr int I_DVP{ 229 };
inline constexpr int I_EHB{ 228 };
inline constexpr int I_EI{ 227 };
inline constexpr int I_ERET{ 226 };
inline constexpr int I_ERETNC{ 225 };
inline constexpr int I_EVP{ 224 };
inline constexpr int I_EXT{ 223 };
inline constexpr int I_FLOOR_L_S{ 222 };
inline constexpr int I_FLOOR_L_D{ 221 };
inline constexpr int I_FLOOR_W_S{ 220 };
inline constexpr int I_FLOOR_W_D{ 219 };
inline constexpr int I_GINVI{ 218 };
inline constexpr int I_GINVT{ 217 };
inline constexpr int I_INS{ 216 };
inline constexpr int I_J{ 215 };
inline constexpr int I_JAL{ 214 };
inline constexpr int I_JALR{ 213 };
inline constexpr int I_JALR_HB{ 212 };
inline constexpr int I_JALX{ 211 };
inline constexpr int I_JIALC{ 210 };
inline constexpr int I_JIC{ 209 };
inline constexpr int I_JR{ 208 };
inline constexpr int I_JR_HB{ 207 };
inline constexpr int I_LB{ 206 };
inline constexpr int I_LBE{ 205 };
inline constexpr int I_LBU{ 204 };
inline constexpr int I_LBUE{ 203 };
inline constexpr int I_LDC{ 202 };
inline constexpr int I_LDXC1{ 201 };
inline constexpr int I_LH{ 200 };
inline constexpr int I_LHE{ 199 };
inline constexpr int I_LHU{ 198 };
inline constexpr int I_LHUE{ 197 };
inline constexpr int I_LL{ 196 };
inline constexpr int I_LLE{ 195 };
inline constexpr int I_LLWP{ 194 };
inline constexpr int I_LLWPE{ 193 };
inline constexpr int I_LSA{ 192 };
inline constexpr int I_LUI{ 191 };
inline constexpr int I_LUXC1{ 190 };
inline constexpr int I_LW{ 189 };
inline constexpr int I_LWC{ 188 };
inline constexpr int I_LWE{ 187 };
inline constexpr int I_LWL{ 186 };
inline constexpr int I_LWLE{ 185 };
inline constexpr int I_LWPC{ 184 };
inline constexpr int I_LWR{ 183 };
inline constexpr int I_LWRE{ 182 };
inline constexpr int I_LWXC1{ 181 };
inline constexpr int I_MADD{ 180 };
inline constexpr int I_MADD_S{ 179 };
inline constexpr int I_MADD_D{ 178 };
inline constexpr int I_MADD_PS{ 177 };
inline constexpr int I_MADDF_S{ 176 };
inline constexpr int I_MADDF_D{ 175 };
inline constexpr int I_MSUBF_S{ 174 };
inline constexpr int I_MSUBF_D{ 173 };
inline constexpr int I_MADDU{ 172 };
inline constexpr int I_MAX_S{ 171 };
inline constexpr int I_MAX_D{ 170 };
inline constexpr int I_MIN_S{ 169 };
inline constexpr int I_MIN_D{ 168 };
inline constexpr int I_MAXA_S{ 167 };
inline constexpr int I_MAXA_D{ 166 };
inline constexpr int I_MINA_S{ 165 };
inline constexpr int I_MINA_D{ 164 };
inline constexpr int I_MFC0{ 163 };
inline constexpr int I_MFC1{ 162 };
inline constexpr int I_MFC2{ 161 };
inline constexpr int I_MFHC0{ 160 };
inline constexpr int I_MFHC1{ 159 };
inline constexpr int I_MFHC2{ 158 };
inline constexpr int I_MFHI{ 157 };
inline constexpr int I_MFLO{ 156 };
inline constexpr int I_MOV_S{ 155 };
inline constexpr int I_MOV_D{ 154 };
inline constexpr int I_MOV_PS{ 153 };
inline constexpr int I_MOVF{ 152 };
inline constexpr int I_MOVF_S{ 151 };
inline constexpr int I_MOVF_D{ 150 };
inline constexpr int I_MOVF_PS{ 149 };
inline constexpr int I_MOVN{ 148 };
inline constexpr int I_MOVN_S{ 147 };
inline constexpr int I_MOVN_D{ 146 };
inline constexpr int I_MOVN_PS{ 145 };
inline constexpr int I_MOVT{ 144 };
inline constexpr int I_MOVT_S{ 143 };
inline constexpr int I_MOVT_D{ 142 };
inline constexpr int I_MOVT_PS{ 141 };
inline constexpr int I_MOVZ{ 140 };
inline constexpr int I_MOVZ_S{ 139 };
inline constexpr int I_MOVZ_D{ 138 };
inline constexpr int I_MOVZ_PS{ 137 };
inline constexpr int I_MSUB{ 136 };
inline constexpr int I_MSUB_S{ 135 };
inline constexpr int I_MSUB_D{ 134 };
inline constexpr int I_MSUB_PS{ 133 };
inline constexpr int I_MSUBU{ 132 };
inline constexpr int I_MTC0{ 131 };
inline constexpr int I_MTC1{ 130 };
inline constexpr int I_MTC2{ 129 };
inline constexpr int I_MTHC0{ 128 };
inline constexpr int I_MTHC1{ 127 };
inline constexpr int I_MTHC2{ 126 };
inline constexpr int I_MTHI{ 125 };
inline constexpr int I_MTLO{ 124 };
inline constexpr int I_MUL{ 123 };
inline constexpr int I_MUH{ 122 };
inline constexpr int I_MULU{ 121 };
inline constexpr int I_MUHU{ 120 };
inline constexpr int I_MUL_S{ 119 };
inline constexpr int I_MUL_D{ 118 };
inline constexpr int I_MUL_PS{ 117 };
inline constexpr int I_MULT{ 116 };
inline constexpr int I_MULTU{ 115 };
inline constexpr int I_NAL{ 114 };
inline constexpr int I_NEG_S{ 113 };
inline constexpr int I_NEG_D{ 112 };
inline constexpr int I_NEG_PS{ 111 };
inline constexpr int I_NMADD_S{ 110 };
inline constexpr int I_NMADD_D{ 109 };
inline constexpr int I_NMADD_PS{ 108 };
inline constexpr int I_NMSUB_S{ 107 };
inline constexpr int I_NMSUB_D{ 106 };
inline constexpr int I_NMSUB_PS{ 105 };
inline constexpr int I_NOP{ 104 };
inline constexpr int I_NOR{ 103 };
inline constexpr int I_OR{ 102 };
inline constexpr int I_ORI{ 101 };
inline constexpr int I_PAUSE{ 100 };
inline constexpr int I_PLL_PS{ 99 };
inline constexpr int I_PLU_PS{ 98 };
inline constexpr int I_PREF{ 97 };
inline constexpr int I_PREFE{ 96 };
inline constexpr int I_PREFX{ 95 };
inline constexpr int I_PUL_PS{ 94 };
inline constexpr int I_PUU_PS{ 93 };
inline constexpr int I_RDHWR{ 92 };
inline constexpr int I_RDPGPR{ 91 };
inline constexpr int I_RECIP_S{ 90 };
inline constexpr int I_RECIP_D{ 89 };
inline constexpr int I_RINT_S{ 88 };
inline constexpr int I_RINT_D{ 87 };
inline constexpr int I_ROTR{ 86 };
inline constexpr int I_ROTRV{ 85 };
inline constexpr int I_ROUND_L_S{ 84 };
inline constexpr int I_ROUND_L_D{ 83 };
inline constexpr int I_ROUND_W_S{ 82 };
inline constexpr int I_ROUND_W_D{ 81 };
inline constexpr int I_RSQRT_S{ 80 };
inline constexpr int I_RSQRT_D{ 79 };
inline constexpr int I_SB{ 78 };
inline constexpr int I_SBE{ 77 };
inline constexpr int I_SC{ 76 };
inline constexpr int I_SCE{ 75 };
inline constexpr int I_SCWP{ 74 };
inline constexpr int I_SCWPE{ 73 };
inline constexpr int I_SDBBP{ 72 };
inline constexpr int I_SDC{ 71 };
inline constexpr int I_SDXC{ 70 };
inline constexpr int I_SEB{ 69 };
inline constexpr int I_SEH{ 68 };
inline constexpr int I_SEL_S{ 67 };
inline constexpr int I_SEL_D{ 66 };
inline constexpr int I_SELEQZ{ 65 };
inline constexpr int I_SELNEZ{ 64 };
inline constexpr int I_SELEQZ_S{ 63 };
inline constexpr int I_SELEQZ_D{ 62 };
inline constexpr int I_SELNEQZ_S{ 61 };
inline constexpr int I_SELNEQZ_D{ 60 };
inline constexpr int I_SH{ 59 };
inline constexpr int I_SHE{ 58 };
inline constexpr int I_SIGRIE{ 57 };
inline constexpr int I_SLL{ 56 };
inline constexpr int I_SLLV{ 55 };
inline constexpr int I_SLT{ 54 };
inline constexpr int I_SLTI{ 53 };
inline constexpr int I_SLTIU{ 52 };
inline constexpr int I_SLTU{ 51 };
inline constexpr int I_SQRT_S{ 50 };
inline constexpr int I_SQRT_D{ 49 };
inline constexpr int I_SRA{ 48 };
inline constexpr int I_SRAV{ 47 };
inline constexpr int I_SRL{ 46 };
inline constexpr int I_SRLV{ 45 };
inline constexpr int I_SSNOP{ 44 };
inline constexpr int I_SUB{ 43 };
inline constexpr int I_SUB_S{ 42 };
inline constexpr int I_SUB_D{ 41 };
inline constexpr int I_SUB_PS{ 40 };
inline constexpr int I_SUBU{ 39 };
inline constexpr int I_SUXC{ 38 };
inline constexpr int I_SW{ 37 };
inline constexpr int I_SWC{ 36 };
inline constexpr int I_SWE{ 35 };
inline constexpr int I_SWL{ 34 };
inline constexpr int I_SWLE{ 33 };
inline constexpr int I_SWR{ 32 };
inline constexpr int I_SWRE{ 31 };
inline constexpr int I_SWXC{ 30 };
inline constexpr int I_SYNC{ 29 };
inline constexpr int I_SYNCI{ 28 };
inline constexpr int I_SYSCALL{ 27 };
inline constexpr int I_TEQ{ 26 };
inline constexpr int I_TEQI{ 25 };
inline constexpr int I_TGE{ 24 };
inline constexpr int I_TGEI{ 23 };
inline constexpr int I_TGEIU{ 22 };
inline constexpr int I_TGEU{ 21 };
inline constexpr int I_TLBINV{ 20 };
inline constexpr int I_TLBINVF{ 19 };
inline constexpr int I_TLBP{ 18 };
inline constexpr int I_TLBR{ 17 };
inline constexpr int I_TLBWI{ 16 };
inline constexpr int I_TLBWR{ 15 };
inline constexpr int I_TLT{ 14 };
inline constexpr int I_TLTI{ 13 };
inline constexpr int I_TLTIU{ 12 };
inline constexpr int I_TLTU{ 11 };
inline constexpr int I_TNE{ 10 };
inline constexpr int I_TNEI{ 9 };
inline constexpr int I_TRUNC_L_S{ 8 };
inline constexpr int I_TRUNC_L_D{ 7 };
inline constexpr int I_TRUNC_W_S{ 6 };
inline constexpr int I_TRUNC_W_D{ 5 };
inline constexpr int I_WAIT{ 4 };
inline constexpr int I_WRPGPR{ 3 };
inline constexpr int I_WSBH{ 2 };
inline constexpr int I_XOR{ 1 };
inline constexpr int I_XORI{ 0 };

}